### PR TITLE
Prepare NPM and TypeScript

### PR DESCRIPTION
**Pull request by blutorange**
I started by merging the state of `mdbassit/Coloris` into the fork and merged the TypeScript declaration file PR. 

Marked as a draft, let me check if I can figure how to convert the code into UMD for NPM without making further merges from `mdbassit/Coloris` too hard. UMD also requires a few adjustments to the `d.ts` file.

Relates to mdbassit/Coloris#14 and mdbassit/Coloris#15

### CODE REVIEW

**Comment by blutorange** [comment]
* The dist build is now an UMD library that loads without side-effects in a module environment and with-side effects (event listeners, DOM modifications, window scope modifications) in a browser environment.
    * Only had to change three lines in the main `coloris.js` file https://github.com/melloware/Coloris/pull/1/commits/c98bb753f9c688bb6f47d0335fe9d6bb20d509e8#diff-ead9bad4168db55a026a34e4cb1a879008aef8132feb6666d49038de3669ec8aL7-L880
* Adjusted the type declaration to reflect that it's now a UMD library.
* Added `dist` to the `.gitignore`. It's on NPM, can be included in release, and makes merging easier because we won't have different build files.
* Changed the package name to `coloris-npm` temporarily for testing purposes until we find a better name.
* Tested the module build in directly in a browser, via webpack, via requirejs and within a TypeScript file

**Comment by blutorange** [comment]
@melloware This package should be in a publishable state now, but would be great if you could build & test it too

I changed the package name to `@melloware/coloris`, if you're username on NPM is `melloware` that [scope should be available to you](https://docs.npmjs.com/about-scopes)

When publishing, you need to explicitly add a flag to make it public:

```bash
npm login

# This will run npm run build automatically
npm publish --access public
```

**Comment by melloware** [comment]
I love it.  One thing I want to consider instead of mine being an attached "fork" of his where it will constantly tell me I am behind or ahead of commits I thought of starting a brand new repo not linked.  Thoughts?  

After I merge this PR of course I will use this code as my starting block!

**Comment by blutorange** [comment]
@melloware Glad I can help :) Regarding the fork, hmm, not sure, but it's really just a github UI issue, I suppose. Merging can be done via `git remote add ...` etc. so I'd say go ahead and start a new repo if you don't need the notifications.

**Comment by melloware** [comment]
worked: https://www.npmjs.com/package/@melloware/coloris

**Pull request merged**
